[workspace]

members = [
    "citadel_workspace_types",
    "citadel_workspace_service",
]

exclude = [
    "./target/*"
]

[workspace.dependencies]
# workspace deps
citadel_workspace_types = { path = "./citadel_workspace_types", default-features = false, version = "0.1.0" }
citadel_workspace_service = { path = "./citadel_workspace_service", default-features = false, version = "0.1.0" }

# standard deps
serde = { version = "1.0.104", default-features = false }
citadel_sdk = { git = "https://github.com/Avarok-Cybersecurity/Citadel-Protocol" }