name: Validate PR
on:
  workflow_call:
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  # 40 MiB stack
  RUST_MIN_STACK: 40971520
  RUST_LOG: "citadel=trace"

jobs:
  tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - uses: Avarok-Cybersecurity/gh-actions-deps@master
      - uses: taiki-e/install-action@nextest
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: cargo nextest run --features=vendored
        if: startsWith(matrix.os, 'windows')
      - run: cargo nextest run
        if: ${{ !startsWith(matrix.os, 'windows') }}

  clippy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: Avarok-Cybersecurity/gh-actions-deps@master
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: rustup component add clippy-preview
      - run: cargo clippy --tests -- -D warnings

  fmt:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: Avarok-Cybersecurity/gh-actions-deps@master
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: cargo fmt --check